# Generated by Django 4.1.1 on 2024-06-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategorieProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_produktu', models.CharField(max_length=255)),
                ('nahled', models.URLField()),
                ('druh_produktu', models.CharField(max_length=255)),
                ('zeme_puvodu', models.CharField(max_length=255)),
                ('kategorie_produktu', models.BooleanField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.TextField()),
                ('ks_skladem', models.IntegerField()),
                ('prumer_hodnoceni', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('registrovan_dne', models.DateTimeField(auto_now_add=True)),
                ('ulice', models.CharField(max_length=255)),
                ('psc', models.CharField(max_length=10)),
                ('mesto', models.CharField(max_length=100)),
                ('oblibene_produkty', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UzivatelOblibene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.produkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.uzivatel')),
            ],
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_objednavky', models.DateTimeField(auto_now_add=True)),
                ('cena_objednavky', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jmeno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('ulice', models.CharField(max_length=255)),
                ('psc', models.CharField(max_length=10)),
                ('mesto', models.CharField(max_length=100)),
                ('kos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.kos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.uzivatel')),
            ],
        ),
        migrations.CreateModel(
            name='KosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cena_celkem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.kos')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='kos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.uzivatel'),
        ),
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnoceni', models.TextField()),
                ('hvezdy', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.produkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.uzivatel')),
            ],
        ),
    ]
